name: build-dpi-examples

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      renode_gitrev:
        description: 'Renode git revision'
        required: false
        default: ''

env:
  RENODE_GITREV: "${{ github.event.inputs.renode_gitrev }}"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: "x86_64", os: "ubuntu-latest"  }
          - { arch: "x86_64", os: "windows-latest" }
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ccache
          key: ${{ runner.os }}-${{ matrix.config.arch }}

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          update: true
          install: >-
            git
            unzip
            wget
            findutils
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      - name: Prepare artifacts for ${{ runner.os }}
        if: ${{ runner.os != 'Windows' }}
        run: |
          set -ex
          RUNNER_OS=${{ runner.os }}
          MAKE_BIN="make"
          BUILD_ARCH=${{ matrix.config.arch }}
          source .github/scripts/build_verilator.sh
          source .github/scripts/build_artifacts.sh
          .github/scripts/download_renode.sh
      
      - name: Prepare artifacts for Windows
        if: ${{ runner.os == 'Windows' }}
        shell: msys2 {0}
        run: |
          set -ex
          RUNNER_OS="Windows"
          MAKE_BIN="mingw32-make.exe"
          BUILD_ARCH=${{ matrix.config.arch }}
          source .github/scripts/build_verilator.sh
          source .github/scripts/build_artifacts.sh
          .github/scripts/download_renode.sh

      - name: Run tests for ${{ runner.os }}
        if: ${{ runner.os != 'Windows' }}
        run: |
          cp artifacts/libcosim_bfm.so renode/
          renode/renode-test -r artifacts/ cosim-axi.robot

      - name: Run tests for Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          cp artifacts/libcosim_bfm.so renode/
          renode/tests/test.bat -r artifacts/ cosim-axi.robot

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: renode-dpi-example-${{ runner.os }}-${{ matrix.config.arch }}-${{ github.run_id }}
          path: artifacts/*
